% What are H,g,A,b ?
H = [6,2,1; 2,5,2; 1,2,4];
g = [-8; -3; -3];
A = [1,0; 0,1; 1,1];
b = [3; 0];
% What are the KKT conditions?
% See notes for derived gradient of lagrange equation and the form which
% the linear system takes.
%% 
% Solve our system with function
[x,lambda] = EqualityQPSolver(H,g,A,b) % produces lambda[2] < 0 ?

%%
% Generate random convex quadratic programs
% We need our function to take in a user defined number and return a
% semi-definite matrix H. Return a full row rank row matrix A which has an
% inverse, i.e. det(A)!=0.
[H,g,A,b,x,lambda] = rand_convex_QP(3)
% Values below are from the rand_convex_QP function and should be the
% same as the EqualityQPSolver gives.

%%
[x,lambda] = EqualityQPSolver(H,g,A,b) 
% Testing the EqualityQPSolver with the randomly generated values it can
% be seen that the results are very similar to values generated by the
% rand_convex_QP function.
%%
% See notes for Write sensitivity equations for the equality constrained
% convex QP. 
% Test sensitivity function on original problem:
[delta_x,delta_lambda] = sensitivity(H,A)
% rows of sensitivities correspond to [g;b], columns correspond to
% [x1;x2;...xn] for delta_x and [lambda1;lambda2;...lambdan] for delta_lambda.
%%
% Solve the dual program
[x,lambda,mu]=EqualityQPSolverDual(H,g,A,b)





